#name: API Testing
#
#on:
#  push:
#    branches:
#      - main
##test1
#jobs:
#  zap_scan:
#    runs-on: ubuntu-latest
#    name: Test and Scan the APIs
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          ref: main
##aja
#      - name: ZAP Scan
#        uses: zaproxy/action-api-scan@v0.7.0
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
#          format: openapi
#          target: 'https://fakerestapi.azurewebsites.net/api/v1/Activities'
#         # target: 'https://uat.jana.sb.tibilprojects.com/switch2/pnotif'
#          custom_headers: |
#            iid: 197
#            iid: 218192
#          cmd_options: >
#            -m POST
#            -d '{
#                  "id": 0,
#                  "title": "string",
#                  "dueDate": "2024-10-25T06:00:13.016Z",
#                  "completed": true
#                }'
#            -J report_json.json
#            -w report_md.md
#            -r report_html.html
#            -a
#
#      - name: Attach the Zap Report To Gmail
#        uses: actions/upload-artifact@v3
#        with:
#          name: Zap Report
#          path: report_html.html
#
#      - name: Test directory
#        run: pwd
#
#      - name: Test
#        run: ls
#
#      - name: Configure Gmail and Send Email
#        env:
#          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
#          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
#          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}  # Replace with the recipient's email
#        run: |
#          python Utilities/send_email.py $GMAIL_USERNAME $GMAIL_PASSWORD $RECIPIENT_EMAIL
#
#




name: API Testing
on:
  push:
    branches:
      - main
#test_personal_git1
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Test and Scan the APIs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

#      - name: Install dependencies
#        run: |
#          pip install -r requirements.txt

      - name: Test directory
        run: pwd

      - name: List files
        run: ls

#      - name: Change directory
#        run: cd /home/runner/work/SoundBox_APP/

#      - name: Run Pytest
       # run: pytest -v -s --capture=tee-sys ./TestScript/Test_app.py --html=./reports/report.html
#        run: pytest ./TestScript/Test_app.py --html-report=./reports/Pytest_report.html



      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          format: openapi
          target: 'https://mqpro-48eab.web.app/login'
          cmd_options: '-J report_json.json -w report_md.md -r report_html.html -a'



      - name: Attach the Test Report To gmail
        uses: actions/upload-artifact@v3
        with:
          name: Test Report
          path: reports/Pytest_report.html

      - name: Attach the Zap Report To Gmail
        uses: actions/upload-artifact@v3
        with:
          name: Test Report
          path: report_html.html

      - name: test directory
        run : pwd

      - name : test
        run : ls

      - name: Attach the Test Logs To Gmail
        uses: actions/upload-artifact@v3
        with:
          name: Test Log
          path: Logs/test.log


      - name: Configure Gmail and Send Email
        env:
          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}  # Replace with the recipient's email
        run: |
          python Utilities/send_email.py $GMAIL_USERNAME $GMAIL_PASSWORD $RECIPIENT_EMAIL














